### ISSUE TITLE
no reference to old terraform version in any import files to be used in sentinel policy

### ISSUE THREAD

**Issue by Mithun2507** [hashicorp/terraform-guides#292] opened 2021-05-06 12:17 UTC
Hi, we are trying to setup a sentinel policy through which we can warn TFE workspace users about the change in the workspace terraform version. so that they can update the TFE codes to avoid any issues after the terraform version is updated from their last code apply. doing this I am trying to refer the import files. tfstate and tfplan both poin to the updated version of workspace so I can not compare them in the policy. another way would be to compare the tfplan's terraform_version with workspace settings. but the tfrun import also doesnot mention the terraform_version it is set to. attached a mock file downloaded after the workspace terraform_version was updated.
please help with a possible solution for this situation
[run-9nL5KCoNJpiQHCxA-sentinel-mocks.tar.gz](https://github.com/hashicorp/terraform-guides/files/6434267/run-9nL5KCoNJpiQHCxA-sentinel-mocks.tar.gz)

**Comment by satishchhatpar** [comment] 2021-05-09 18:59
@Mithun2507 I will try executing mock files. I am new to terraform. I am learning.

**Comment by rberlind** [comment] 2021-08-11 21:10
@Mithun2507 : Apologies for not seeing your issue much sooner.  You are correct that terraform_version in both tfplan/v2 and tfstate/v2 point to the new version set on the workspace.  That could be viewed as a bug since the version for the state should really be the version that existed in the last state file. But the issue here appears to be with the data returned by `terraform show -json` which shows up in the raw portion of the tfplan/v2 import and is where Sentinel gets all its data from including the data in the tfplan/v2 and tfconfig/v2 imports.  I will file an internal ticket about this.  For now, I'm going to close this issue since it is not a problem with any of the example policies in this repository. If you want, you could file an issue against the hashicorp/terraform repository to point out that the value of `terraform_version` under `prior_state` is not the actual version of the prior state if the terraform version has been changed in the workspace.

**Closed by rberlind** 2021-08-11 21:10 UTC

**Comment by rberlind** [comment] 2021-08-18 16:26
@Mithun2507 : The Sentinel team has confirmed that the issue is with the `terraform show -json` command within Terraform Core.  The Sentinel and Core teams will work on a solution or workaround.  I cannot yet give you a timeframe for this to be addressed.
